### ISSUE TITLE
您好，请教个问题 

### ISSUE THREAD

**Issue by SynChron1zed** [awaw00/react-curd#1]
我现在发送请求 获取 access-token 的值获取不到 是怎么回事 

![Uploading image.png…]()

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/25945268/ddbcc72e-3678-11e7-8a60-112d494029c6.png)

**Comment by SynChron1zed** [comment]
![image](https://cloud.githubusercontent.com/assets/18717051/25945282/ebff5608-3678-11e7-964f-589bfc6ecd7b.png)

**Comment by SynChron1zed** [comment]
但是图上 确有 a-t的值  问下大概哪里出了问题了么

**Comment by awaw00** [comment]
你好，服务端需要添加一个返回头 'Access-Control-Expose-Headers': 'access-token'
参考：https://github.com/awaw00/react-curd/blob/master/server/index.js#L11
