### ISSUE TITLE
roadhog build生成dist,发布后访问无css样式

### ISSUE THREAD

**Issue by lvsike** [awaw00/react-curd#8]
应该是roadhog版本升级导致的吧,解决步骤如下:
1.因为public下文件默认会被拷贝至dist目录, 所以将index.html从public中移出放在src下, 后缀改为ejs.
2.roadhog 2.0的配置文件从 .roadhogrc 更名为 .webpackrc, 所以将其更名为.webpackrc, 在其中增加配置`  html: {
    template: './src/index.ejs'
  },`
3.roadhog build即可.

**Comment by awaw00** [comment]
已解决就关了，工具问题最好到工具相关git去提issue
